import initSmoothScroll from "./modules/scroll-suave.js";
import initAnimationScroll from "./modules/scroll-animacao.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/tabnav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initOpeningHours from "./modules/openingHours.js";
import initFetchBitcoin from "./modules/fetch-bitcoins.js";
import initFetchAnimals from "./modules/fetch-animals.js";
initSmoothScroll();
initAnimationScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initOpeningHours();
initFetchBitcoin();
initFetchAnimals();
